name: Build LaTeX

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'LICENSE-template'
      - '.gitignore'

  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'LICENSE-template'
      - '.gitignore'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: 00-main.tex
          args: -pdf -interaction=nonstopmode -halt-on-error -file-line-error -jobname=WANG-DISSERTATION-2026

      - name: Upload PDF
        uses: actions/upload-artifact@v7
        with:
          name: dissertation
          path: WANG-DISSERTATION-2026.pdf
          retention-days: 90
